#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: FX JavaDevBlog
title: FX JavaDevBlog

index:
    fr: "/index-fr.html"
    en: "/index-en.html"

# Short bio or description (displayed in the header)
t:
    fr: 
        description: "Java / APIs / Linux / RetroBidules et plus ..."
        name: "FX JavaDevBlog"
        title: "FX JavaDevBlog"
        search: "Chercher sur ce site"
        table_of_contents: "Sommaire"
        published: "Publié le"
        available_languages: "View this post in other language > "
        comments: "Commentaires"
        other_articles: "Mes autres articles"
        share_article: "Partage cet article sur"
        read_more: "Lire plus ..."

        menu:
            articles: 
                url: "/"
                text: "Articles"
            st-programming:
                url: "/st-programming/"
                text: "ST-Programming"
            blanka: 
                url: "/blanka-cave/fr/"
                text: "Grotte de Blanka"
            tips: 
                url: "/astuces/"
                text: "Astuces"
            links:
                url: "/links/en/"     
                text: "Liens"
            about: 
                url: "/about/"
                text: "A Propos"
    en:
        description: "Java / APIs / Linux / RetroStuffs and more..."
        name: "FX JavaDevBlog"
        title: "FX JavaDevBlog" 
        search: "Search this site"
        table_of_contents: "Table of content"
        published: "Publication date :"
        available_languages: "View this post in other language > "
        comments: "Comments"
        other_articles: "My other articles"
        share_article: "Share this article on"
        read_more: "Read more ..."

        menu:
            articles: 
                url: "/"
                text: "Articles"
            st-programming:
                url: "/st-programming/"
                text: "ST-Programming"
            blanka: 
                url: "/blanka-cave/en/"
                text: "Blanka Cave"
            tips: 
                url: "/astuces/"
                text: "Tips"
            links:
                url: "/links/en/"    
                text: "Links"
            about: 
                url: "/about/"
                text: "About"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/new-java-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  twitter: fxrobin75
  dribbble:
  email: 
  facebook:
  flickr:
  github: fxrobin
  instagram:
  linkedin: fxrobin
  pinterest:
  rss: true
  stackoverflow: users/3017541/fxrobin
  youtube: channel/UCt0Bicvr4OrHmk0M8_50VPQ?
  googleplus: # anything in your profile username that comes after plus.google.com/

excerpt_separator: "<!--excerpt-->"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: fxrobin-github-io

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-114271874-1

#remote_theme: pages-themes/hacker
#theme: jekyll-theme-hacker



# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.fxjavadevblog.fr

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

paginate: 3

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap 
  - jekyll-feed
  - jekyll-seo-tag



# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


